### ISSUE TITLE
Add support for optional PathParameters

### ISSUE THREAD

**Issue by fsavina** [calcinai/strut#1]
The [PathParameterSubSchema](https://github.com/calcinai/strut/blob/master/src/Definitions/PathParameterSubSchema.php) parameter should accept `false` as a valid value for the `required` property.

**Comment by calcinai** [comment]
Het @fsavina are you sure? In the spec it shows it as only being allowed `true`:

https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json#L824

**Comment by fsavina** [comment]
That's fair. But what if for some reason I need to switch a parameter `required` property from `true` to `false` during the same execution? Would it be possible to add an `unset` method on the BaseSchema object to remove the `required` property?

**Comment by calcinai** [comment]
Can you give an example? From what I can see, the schema would be invalid if it contained a `false`

**Comment by fsavina** [comment]
I agree with that. That's why I'm asking if you could add a function to remove a previously set property on a Schema.

**Comment by calcinai** [comment]
Ah I see, you're meaning that you have an invalid schema that you'd like to correct?

**Comment by fsavina** [comment]
I am generating a schema at runtime and the properties might change at different points of the execution.
Something like `$param->remove('required')` could help me remove that property instead of setting it to `false` when it was previously set to `true`.

**Comment by calcinai** [comment]
That makes more sense (although I still can't see how it'd ever get set to `true` in the first place!), so you're after a generic method in the base schema.  

Can you make a PR?

**Comment by fsavina** [comment]
Of course! #2
